# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dummy_arm_controller
    - dummy_hand_controller

  dummy_arm_controller:
    action_ns: follow_joint_trajectory  # 添加此行
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  dummy_hand_controller:
    action_ns: follow_joint_trajectory  # 添加此行
    type: FollowJointTrajectory
    joints:
      - panda_finger_joint1