# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dummy_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    dummy_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dummy_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
dummy_hand_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity